baseurl = "./"
title = "Cryptopower"
languageCode = "en-us"

[params]
  favicon = "../images/cryptopower.png"
  main = "CRYPTOPOWER"
  info = "A cross-platform SPV (DCR, BTC & LTC) privacy wallet built with go."

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1