baseurl = "./"
title = "Cryptopower"
languageCode = "en-us"

[params]

    favicon = "../images/favicon-32x32.png"
    main = "Cryptopower"
    info = "A cross-platform desktop SPV multichain (DCR, BTC & LTC) wallet built with gio."


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1